export default Object.freeze({
  BOARD__SET_BOARD: 'BOARD__SET_BOARD',
  BOARD__LOAD_BOARD: 'BOARD__LOAD_BOARD',
  BOARD__SET_REFRESH: 'BOARD__SET_REFRESH',
  BOARD__UPDATE_LIST_ORDER: 'BOARD__UPDATE_LIST_ORDER',
  BOARD__OPEN_MODAL_WITH_CARD: 'BOARD__OPEN_MODAL_WITH_CARD',
  BOARD__CLOSE_MODAL: 'BOARD__CLOSE_MODAL',
});
